blank_issues_enabled: false
contact_links:
  - name: 🧑‍💻 ¿Buscás Grupo / Integrantes? ¡Posteá ACA!
    url: https://github.com/sisoputnfrba/foro/issues/2011
    about: Post de búsqueda de grupos o integrantes.