blank_issues_enabled: false
contact_links:
 - name: Busco grupo o integrantes
   url: https://faq.utnso.com.ar/issue-grupos
   about: Posteá acá si te encontrás en búsqueda de grupo o integrantes para realizar el TP.
