blank_issues_enabled: false
contact_links:
  - name: Cambios de grupos? Encontrá un carpincho amigo en este issue!
    url: https://github.com/sisoputnfrba/foro/issues/2320
    about: Post de búsqueda de grupos o integrantes. 
