blank_issues_enabled: false
contact_links:
  - name: 👩‍💻 Buscas Grupo / Integrantes para el 2c2021? Postea ACA! 👨‍💻
    url: https://github.com/sisoputnfrba/foro/issues/2293
    about: Post de búsqueda de grupos o integrantes. 
