blank_issues_enabled: false
contact_links:
  - name: 🚀🚀 Cambios de Grupo - Busca para completar tu tripulación 🚀🚀
    url: https://github.com/sisoputnfrba/foro/issues/2069
    about: En este thread van a poder buscar integrantes para completar su grupo o grupo en caso de haberse quedado solos.
