blank_issues_enabled: false
contact_links:
  - name: Tengo una consulta administrativa
    url: mailto:inscripciones@utnso.com.ar
    about: Se pueden realizar consultas administrativas enviando un mail a `inscripciones@utnso.com.ar`
